#!/usr/bin/env bash
# Adds required entries for localhost and facebook.com to /etc/hosts (sets localhost to 127.0.0.2 and facebook.com to 8.8.8.8)

echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" | sudo tee /etc/hosts
