#!/usr/bin/env bash
# Adds the requested resolutions to /etc/hosts (requires sudo)

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
